"""added cascade deletions

Revision ID: 08c52b5f0aee
Revises: 8c74bd413366
Create Date: 2026-03-01 10:22:22.579570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c52b5f0aee'
down_revision: Union[str, Sequence[str], None] = '8c74bd413366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accountsettings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('accountsettings_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'account', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accountsettings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('accountsettings_user_id_fkey'), 'account', ['user_id'], ['id'])

    # ### end Alembic commands ###
