"""make start and stop timestamps optional

Revision ID: 73a92a356a33
Revises: 08c52b5f0aee
Create Date: 2026-03-10 14:42:48.095127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a92a356a33'
down_revision: Union[str, Sequence[str], None] = '08c52b5f0aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timerecord', schema=None) as batch_op:
        batch_op.alter_column('start_ts',
               nullable=True)
        batch_op.alter_column('end_ts',
               nullable=True)
        batch_op.alter_column('total_time_minutes',
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timerecord', schema=None) as batch_op:
        batch_op.alter_column('total_time_minutes',
               nullable=False)
        batch_op.alter_column('end_ts',
               nullable=False)
        batch_op.alter_column('start_ts',
               nullable=False)

    # ### end Alembic commands ###
