"""empty message

Revision ID: 8c74bd413366
Revises: 
Create Date: 2026-03-01 10:01:37.795363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8c74bd413366'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accountsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_rate', sa.Float(), nullable=False),
    sa.Column('current_increment', sa.Integer(), nullable=False),
    sa.Column('current_rounding', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incrementhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('increment', sa.Integer(), nullable=False),
    sa.Column('effective_ts', sa.DateTime(), nullable=False),
    sa.Column('effective_tz', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratehistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('effective_ts', sa.DateTime(), nullable=False),
    sa.Column('effective_tz', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roundinghistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rounding', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effective_ts', sa.DateTime(), nullable=False),
    sa.Column('effective_tz', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_ts', sa.DateTime(), nullable=False),
    sa.Column('end_ts', sa.DateTime(), nullable=False),
    sa.Column('total_time_minutes', sa.Integer(), nullable=False),
    sa.Column('atoe_timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('atoe_rate', sa.Float(), nullable=False),
    sa.Column('atoe_rounding', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('atoe_increment', sa.Integer(), nullable=False),
    sa.Column('atoe_break_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('amount_earned', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timerecord')
    op.drop_table('roundinghistory')
    op.drop_table('ratehistory')
    op.drop_table('incrementhistory')
    op.drop_table('accountsettings')
    op.drop_table('account')
    # ### end Alembic commands ###
